name: similar_web
description: An API consumer for "Similar Web" web statistics service. Use this if you want to know estimated data for web traffic of non-owned pages
version: 0.0.1+1
repository: https://github.com/Rodsevich/similar_web

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_mappable: ^3.2.0
  dio: ^5.3.2

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.2.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
