name: similar_web
description: An API consumer for "Similar Web" web statistics service. Use this if you want to know estimated data of web traffic of non-owned pages
version: 0.1.0+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
