name: similar_web
description: An API consumer for "Similar Web" web statistics service. Use this if you want to know estimated data for web traffic of non-owned pages
version: 0.0.1+1


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^5.3.2

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
